# Generated by Django 2.0.6 on 2018-10-26 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0004_usercollect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercollect',
            name='UC_Article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NTWebsite.TopicArticleStatistic', verbose_name='文章ID'),
        ),
    ]
