# Generated by Django 2.0.6 on 2018-10-31 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0005_auto_20181026_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='AC_Parent',
            field=models.CharField(default='', editable=False, max_length=100, verbose_name='父评论ID'),
        ),
    ]
