# Generated by Django 2.0.6 on 2018-10-31 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0006_auto_20181031_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='AC_Parent',
            field=models.CharField(default='', max_length=100, verbose_name='父评论ID'),
        ),
    ]
