# Generated by Django 2.0.6 on 2018-11-02 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0007_auto_20181031_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentUserLikesOrDislikesTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CLD_StandPoint', models.IntegerField(verbose_name='立场代码')),
                ('CLD_EditDate', models.DateField(auto_now=True, verbose_name='时间')),
                ('CLD_ArticleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NTWebsite.ArticleComment', verbose_name='评论ID')),
                ('CLD_UserNickName', models.ForeignKey(default='flysafely', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='用户名')),
            ],
            options={
                'verbose_name_plural': '评论立场统计',
            },
        ),
    ]
