# Generated by Django 2.0.6 on 2018-11-02 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0008_commentuserlikesordislikestable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentuserlikesordislikestable',
            old_name='CLD_ArticleID',
            new_name='CLD_CommentID',
        ),
    ]
