# Generated by Django 2.0.6 on 2018-11-03 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0009_auto_20181102_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlecomment',
            old_name='AC_Dislikes',
            new_name='AC_Dislike',
        ),
        migrations.RenameField(
            model_name='articlecomment',
            old_name='AC_Likes',
            new_name='AC_Like',
        ),
    ]
