# Generated by Django 2.0.6 on 2018-11-12 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0010_auto_20181103_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTable',
            fields=[
                ('NT_ID', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='通知ID')),
                ('NT_Plate', models.CharField(max_length=30, verbose_name='板块')),
                ('NT_TargetUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='被通知者')),
            ],
            options={
                'verbose_name_plural': '通知信息',
            },
        ),
        migrations.CreateModel(
            name='RollCallDialogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RCD_Location', models.CharField(max_length=1, verbose_name='所处位置')),
                ('RCD_EditDate', models.DateField(auto_now=True, verbose_name='编辑时间')),
                ('RCD_Info', models.CharField(max_length=30, verbose_name='对话内容')),
            ],
            options={
                'verbose_name_plural': '点名对话',
            },
        ),
        migrations.CreateModel(
            name='RollCallInfo',
            fields=[
                ('RCI_ID', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='点名ID')),
                ('RCI_Title', models.CharField(max_length=35, unique=True, verbose_name='点名标题')),
                ('RCI_Dialogue', models.TextField(max_length=1000, verbose_name='点名描述')),
                ('RCI_EditDate', models.DateField(auto_now=True, verbose_name='编辑时间')),
                ('RCI_LeftLike', models.IntegerField(default=0, verbose_name='点名者支持数')),
                ('RCI_RightLike', models.IntegerField(default=0, verbose_name='被点名者支持数')),
                ('RCI_IsRead', models.IntegerField(default=0, verbose_name='是否已阅')),
                ('RCI_Publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Publisher_User', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='点名者')),
                ('RCI_Target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Target_User', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='被点名者')),
            ],
            options={
                'verbose_name_plural': '点名信息',
            },
        ),
        migrations.AddField(
            model_name='rollcalldialogue',
            name='RCD_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NTWebsite.RollCallInfo', verbose_name='点名信息'),
        ),
    ]
