# Generated by Django 2.0.6 on 2018-11-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0011_auto_20181112_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rollcalldialogue',
            name='RCD_Info',
        ),
        migrations.RemoveField(
            model_name='rollcalldialogue',
            name='RCD_Location',
        ),
        migrations.AddField(
            model_name='rollcalldialogue',
            name='RCD_Query',
            field=models.CharField(default='', max_length=30, verbose_name='询问内容'),
        ),
        migrations.AddField(
            model_name='rollcalldialogue',
            name='RCD_Reply',
            field=models.CharField(default='', max_length=30, verbose_name='回复内容'),
        ),
    ]
