# Generated by Django 2.0.6 on 2018-11-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0013_auto_20181113_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='rollcallinfo',
            name='RCI_Read',
            field=models.IntegerField(default=0, verbose_name='点名阅读量'),
        ),
    ]
