# Generated by Django 2.0.6 on 2018-11-27 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0015_rollcallreadsip'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCircuseeCollect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UCC_CollectTime', models.DateField(auto_now=True, verbose_name='时间')),
                ('UCC_RollCall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NTWebsite.RollCallInfo', verbose_name='点名ID')),
                ('UCC_UserNickName', models.ForeignKey(default='flysafely', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='用户名')),
            ],
            options={
                'verbose_name_plural': '用户围观',
            },
        ),
        migrations.AlterModelOptions(
            name='usercollect',
            options={'verbose_name_plural': '用户文章收藏'},
        ),
    ]
