# Generated by Django 2.0.6 on 2018-12-03 07:47

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0016_auto_20181127_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialTopicInfo',
            fields=[
                ('STI_ID', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='专题ID')),
                ('STI_Title', models.CharField(max_length=35, unique=True, verbose_name='专题标题')),
                ('STI_Cover', models.ImageField(upload_to='Cover')),
                ('STI_EditDate', models.DateField(auto_now=True, verbose_name='发布时间')),
                ('STI_Type', models.CharField(default='article', max_length=10, verbose_name='专题类型')),
                ('STI_Follower', models.IntegerField(default=0, verbose_name='关注量')),
                ('STI_Hot', models.IntegerField(default=10, verbose_name='热度')),
                ('STI_Content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='正文')),
                ('STI_Publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Publisher', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='点名者')),
            ],
            options={
                'verbose_name_plural': '**3**专题信息**3**',
            },
        ),
    ]
