# Generated by Django 2.0.6 on 2018-12-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0017_specialtopicinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialtopicinfo',
            name='STI_Cover',
            field=models.ImageField(upload_to='Cover', verbose_name='专题封面'),
        ),
    ]
