# Generated by Django 2.0.6 on 2018-12-03 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0018_auto_20181203_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialTopicCollect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STC_CollectTime', models.DateField(auto_now=True, verbose_name='时间')),
                ('STC_SpecialTopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NTWebsite.SpecialTopicInfo', verbose_name='专题ID')),
                ('STC_UserNickName', models.ForeignKey(default='flysafely', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='用户名')),
            ],
            options={
                'verbose_name_plural': '专题关注',
            },
        ),
    ]
