# Generated by Django 2.0.6 on 2018-12-03 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0019_specialtopiccollect'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialtopiccollect',
            options={'verbose_name_plural': '**3**专题关注**3**'},
        ),
    ]
