# Generated by Django 2.0.6 on 2018-12-04 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0021_remove_specialtopicinfo_sti_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialtopicinfo',
            name='STI_Cover',
            field=models.ImageField(default='', upload_to='Cover', verbose_name='专题封面'),
        ),
    ]
