# Generated by Django 2.0.6 on 2018-12-04 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0022_specialtopicinfo_sti_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialtopicinfo',
            old_name='STI_Cover',
            new_name='STICover',
        ),
    ]
