# Generated by Django 2.0.6 on 2018-12-04 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0023_auto_20181204_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialtopicinfo',
            old_name='STICover',
            new_name='STI_Cover',
        ),
    ]
