# Generated by Django 2.0.6 on 2018-12-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0027_auto_20181204_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialtopicinfo',
            name='STI_Abstract',
            field=models.CharField(default='', max_length=30, verbose_name='简介'),
        ),
    ]
