# Generated by Django 2.0.6 on 2018-12-04 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0028_specialtopicinfo_sti_abstract'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialTopicReadsIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STR_IP', models.CharField(blank=True, max_length=100, null=True, verbose_name='IP')),
                ('STR_EditDate', models.DateField(auto_now=True, verbose_name='时间')),
                ('STR_SpecialTopicID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NTWebsite.SpecialTopicInfo', verbose_name='专题ID')),
            ],
            options={
                'verbose_name_plural': '**3**专题阅读IP统计**3**',
            },
        ),
    ]
