# Generated by Django 2.0.6 on 2018-12-04 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0029_specialtopicreadsip'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialTopicComment',
            fields=[
                ('STC_ID', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='专题评论ID')),
                ('STC_Comment', models.TextField(verbose_name='评论内容')),
                ('STC_Parent', models.CharField(default='', max_length=100, verbose_name='父评论ID')),
                ('STC_EditDate', models.DateTimeField(auto_now=True, verbose_name='编辑时间')),
                ('STC_Readstatus', models.CharField(choices=[('Y', '已阅'), ('N', '未读')], default='N', max_length=1, verbose_name='是否阅读')),
                ('STC_SpecialTopicID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NTWebsite.SpecialTopicInfo', verbose_name='专题ID')),
                ('STC_UserNickName', models.ForeignKey(default='flysafely', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='用户名')),
            ],
            options={
                'verbose_name_plural': '**3**专题评论**3**',
            },
        ),
    ]
