# Generated by Django 2.0.6 on 2018-12-05 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0030_specialtopiccomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialtopicinfo',
            name='STI_Publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Publisher', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='发布者'),
        ),
    ]
