# Generated by Django 2.0.6 on 2018-12-05 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0031_auto_20181205_1643'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpecialTopicCollect',
            new_name='SpecialTopicFollow',
        ),
        migrations.RenameField(
            model_name='specialtopicfollow',
            old_name='STC_CollectTime',
            new_name='STF_CollectTime',
        ),
        migrations.RenameField(
            model_name='specialtopicfollow',
            old_name='STC_SpecialTopic',
            new_name='STF_SpecialTopic',
        ),
        migrations.RenameField(
            model_name='specialtopicfollow',
            old_name='STC_UserNickName',
            new_name='STF_UserNickName',
        ),
    ]
