# Generated by Django 2.0.6 on 2018-12-11 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0036_specialtopicinfo_sti_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RA_Rank', models.IntegerField(default=0, verbose_name='顺序')),
                ('RA_Author', models.ForeignKey(default='flysafely', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='用户名')),
            ],
            options={
                'verbose_name_plural': '**1**推荐用户**1**',
            },
        ),
    ]
