# Generated by Django 2.0.6 on 2018-12-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0037_recommendauthor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecomment',
            options={'verbose_name_plural': '**1**文章评论**1**'},
        ),
        migrations.AlterModelOptions(
            name='articlereadsip',
            options={'verbose_name_plural': '**1**文章阅读IP统计**1**'},
        ),
        migrations.AlterModelOptions(
            name='articletags',
            options={'verbose_name_plural': '**1**文章标签**1**'},
        ),
        migrations.AlterModelOptions(
            name='articleuserlikesordislikestable',
            options={'verbose_name_plural': '**1**文章立场统计**1**'},
        ),
        migrations.AlterModelOptions(
            name='categoryinfo',
            options={'verbose_name_plural': '**1**来自类目**1**'},
        ),
        migrations.AlterModelOptions(
            name='commentuserlikesordislikestable',
            options={'verbose_name_plural': '**1**评论立场统计**1**'},
        ),
        migrations.AlterModelOptions(
            name='configparams',
            options={'verbose_name_plural': '*****配置参数*****'},
        ),
        migrations.AlterModelOptions(
            name='notificationtable',
            options={'verbose_name_plural': '**4**通知信息**4**'},
        ),
        migrations.AlterModelOptions(
            name='preferredconfigname',
            options={'verbose_name_plural': '*****首选配置设置*****'},
        ),
        migrations.AlterModelOptions(
            name='rollcalldialogue',
            options={'verbose_name_plural': '**2**点名对话明细**2**'},
        ),
        migrations.AlterModelOptions(
            name='rollcallinfo',
            options={'verbose_name_plural': '**2**点名基础信息**2**'},
        ),
        migrations.AlterModelOptions(
            name='rollcallreadsip',
            options={'verbose_name_plural': '**2**围观IP统计**2**'},
        ),
        migrations.AlterModelOptions(
            name='topicarticlestatistic',
            options={'verbose_name_plural': '**1**文章基础信息**1**'},
        ),
        migrations.AlterModelOptions(
            name='topicarticletheme',
            options={'verbose_name_plural': '**1**文章主题**1**'},
        ),
        migrations.AlterModelOptions(
            name='usercircuseecollect',
            options={'verbose_name_plural': '**2**用户围观**2**'},
        ),
        migrations.AlterModelOptions(
            name='usercollect',
            options={'verbose_name_plural': '**1**文章用户收藏**1**'},
        ),
        migrations.AddField(
            model_name='notificationtable',
            name='NT_KeyID',
            field=models.CharField(default='', max_length=100, verbose_name='关键ID'),
        ),
    ]
