# Generated by Django 2.0.6 on 2018-12-13 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0038_auto_20181213_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlink',
            options={'verbose_name_plural': '**4**用户关注信息**4**'},
        ),
    ]
