# Generated by Django 2.0.6 on 2018-12-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0039_auto_20181213_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtable',
            name='NT_Sign',
            field=models.CharField(default='', max_length=30, verbose_name='标记'),
        ),
    ]
