# Generated by Django 2.0.6 on 2018-12-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0041_auto_20181217_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='UT_CommentCount',
            field=models.IntegerField(default=0, verbose_name='评论数量'),
        ),
        migrations.AddField(
            model_name='user',
            name='UT_FansCount',
            field=models.IntegerField(default=0, verbose_name='关注者数量'),
        ),
        migrations.AddField(
            model_name='user',
            name='UT_FoucusCount',
            field=models.IntegerField(default=0, verbose_name='关注数量'),
        ),
        migrations.AddField(
            model_name='user',
            name='UT_TopicsCount',
            field=models.IntegerField(default=0, verbose_name='文章数量'),
        ),
    ]
