# Generated by Django 2.0.6 on 2018-12-25 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0043_auto_20181221_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtable',
            name='NT_SourceUser',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='SourceUser', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='通知者'),
        ),
        migrations.AlterField(
            model_name='notificationtable',
            name='NT_TargetUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TargetUser', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='被通知者'),
        ),
    ]
