# Generated by Django 2.0.6 on 2018-12-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0046_auto_20181226_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtable',
            name='NT_Title',
            field=models.CharField(default='', max_length=100, verbose_name='标题'),
        ),
    ]
