# Generated by Django 2.0.6 on 2018-12-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0047_notificationtable_nt_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='configparams',
            name='CP_RollCallsPageLimit',
            field=models.IntegerField(default=10, verbose_name='每页点名数量'),
        ),
        migrations.AddField(
            model_name='configparams',
            name='CP_SpecialTopicsPageLimit',
            field=models.IntegerField(default=10, verbose_name='每页专题数量'),
        ),
    ]
