# Generated by Django 2.0.6 on 2018-12-30 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0049_notificationtable_nt_anchorid'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('BL_ID', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='黑名单ID')),
                ('BL_Handler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BL_Handler', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='操作用户')),
                ('BL_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BL_User', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='被添加用户')),
            ],
            options={
                'verbose_name_plural': '**6**通知信息**6**',
            },
        ),
    ]
