# Generated by Django 2.0.6 on 2019-01-02 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0050_blacklist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blacklist',
            options={'verbose_name_plural': '**6**黑名单**6**'},
        ),
    ]
