# Generated by Django 2.0.6 on 2019-01-03 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0051_auto_20190102_1604'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='configparams',
            table='配置测试',
        ),
    ]
