# Generated by Django 2.0.6 on 2019-01-03 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0052_auto_20190103_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configparams',
            options={'verbose_name': '*****配置参数*****', 'verbose_name_plural': '*****配置参数*****'},
        ),
        migrations.AlterModelTable(
            name='configparams',
            table=None,
        ),
    ]
