# Generated by Django 2.0.6 on 2019-01-03 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0053_auto_20190103_1713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecomment',
            options={'verbose_name': '评论', 'verbose_name_plural': '**1**文章评论**1**'},
        ),
        migrations.AlterModelOptions(
            name='articlereadsip',
            options={'verbose_name': '阅读IP记录', 'verbose_name_plural': '**1**文章阅读IP统计**1**'},
        ),
        migrations.AlterModelOptions(
            name='articletags',
            options={'verbose_name': '标签', 'verbose_name_plural': '**1**文章标签**1**'},
        ),
        migrations.AlterModelOptions(
            name='articleuserlikesordislikestable',
            options={'verbose_name': '立场记录', 'verbose_name_plural': '**1**文章立场统计**1**'},
        ),
        migrations.AlterModelOptions(
            name='blacklist',
            options={'verbose_name': '记录', 'verbose_name_plural': '**6**黑名单**6**'},
        ),
        migrations.AlterModelOptions(
            name='categoryinfo',
            options={'verbose_name': '类目', 'verbose_name_plural': '**1**来自类目**1**'},
        ),
        migrations.AlterModelOptions(
            name='commentuserlikesordislikestable',
            options={'verbose_name': '评论立场记录', 'verbose_name_plural': '**1**评论立场统计**1**'},
        ),
        migrations.AlterModelOptions(
            name='configparams',
            options={'verbose_name': '配置参数', 'verbose_name_plural': '*****配置参数*****'},
        ),
        migrations.AlterModelOptions(
            name='notificationtable',
            options={'verbose_name': '信息', 'verbose_name_plural': '**4**通知信息**4**'},
        ),
        migrations.AlterModelOptions(
            name='preferredconfigname',
            options={'verbose_name': '首选配置', 'verbose_name_plural': '*****首选配置设置*****'},
        ),
        migrations.AlterModelOptions(
            name='recommendauthor',
            options={'verbose_name': '用户', 'verbose_name_plural': '**1**推荐用户**1**'},
        ),
        migrations.AlterModelOptions(
            name='rollcalldialogue',
            options={'verbose_name': '对话记录', 'verbose_name_plural': '**2**点名对话明细**2**'},
        ),
        migrations.AlterModelOptions(
            name='rollcallinfo',
            options={'verbose_name': '点名信息', 'verbose_name_plural': '**2**点名基础信息**2**'},
        ),
        migrations.AlterModelOptions(
            name='rollcallreadsip',
            options={'verbose_name': 'IP记录', 'verbose_name_plural': '**2**围观IP统计**2**'},
        ),
        migrations.AlterModelOptions(
            name='specialtopiccomment',
            options={'verbose_name': '评论', 'verbose_name_plural': '**3**专题评论**3**'},
        ),
        migrations.AlterModelOptions(
            name='specialtopicfollow',
            options={'verbose_name': '关注', 'verbose_name_plural': '**3**专题关注**3**'},
        ),
        migrations.AlterModelOptions(
            name='specialtopicinfo',
            options={'verbose_name': '专题', 'verbose_name_plural': '**3**专题信息**3**'},
        ),
        migrations.AlterModelOptions(
            name='specialtopicreadsip',
            options={'verbose_name': 'IP记录', 'verbose_name_plural': '**3**专题阅读IP统计**3**'},
        ),
        migrations.AlterModelOptions(
            name='topicarticlestatistic',
            options={'verbose_name': '文章信息', 'verbose_name_plural': '**1**文章基础信息**1**'},
        ),
        migrations.AlterModelOptions(
            name='topicarticletheme',
            options={'verbose_name': '文章', 'verbose_name_plural': '**1**文章主题**1**'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='usercircuseecollect',
            options={'verbose_name': '围观', 'verbose_name_plural': '**2**用户围观**2**'},
        ),
        migrations.AlterModelOptions(
            name='usercollect',
            options={'verbose_name': '文章收藏', 'verbose_name_plural': '**1**文章用户收藏**1**'},
        ),
        migrations.AlterModelOptions(
            name='userlink',
            options={'verbose_name': '关注信息', 'verbose_name_plural': '**4**用户关注信息**4**'},
        ),
    ]
