# Generated by Django 2.0.6 on 2019-01-07 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0055_auto_20190106_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configparams',
            name='CP_ReadsThreshold',
            field=models.CharField(default=10, max_length=20, verbose_name='阅读量阈值'),
        ),
    ]
